name: 🐞 Bug 反馈
description: 反馈遇到的问题
title: '[BUG] '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # 反馈须知

        在反馈问题之前，请仔细[检查](https://github.com/BiliRoamingX/BiliRoamingX/issues?q=label%3Abug)此问题是否已经反馈过，避免重复反馈。

  - type: input
    attributes:
      label: 系统版本
      placeholder: 例如 MIUI 14
    validations:
      required: true

  - type: input
    attributes:
      label: Android 版本
      placeholder: 例如 13
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 哔哩哔哩版本
      options:
        - 粉版（普通版）
        - HD 版
        - Play 版（国际版）
      description: 目前仅支持粉版、HD 版、Play 版
    validations:
      required: true

  - type: input
    attributes:
      label: 哔哩哔哩版本号
      placeholder: 例如 7.40.0
      description: 非最新版本可能不受理
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 发生了什么？有什么现状？
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现步骤
      description: 如何复现
      placeholder: |
        1. 打开...
        2. 点击...
        3. 出现...状况
    validations:
      required: true

  - type: textarea
    attributes:
      label: 日志
      description: 请开启哔哩漫游X设置关于页面里的调试模式，若能复现则复现一遍，点击分享日志选项将日志上传到此。
      placeholder: 点击文本框下面小长条可以上传文件
    validations:
      required: true

  - type: textarea
    attributes:
      label: 截图或录屏
      description: 问题复现时的截图或录屏
      placeholder: 点击文本框下面小长条可以上传文件
    validations:
      required: false

  - type: textarea
    attributes:
      label: 解决办法
      description: 如果可能，给出一个可行的解决办法。
    validations:
      required: false

  - type: textarea
    attributes:
      label: 补充信息
      description: 例如视频BV号，番剧名。
    validations:
      required: false
