name: ⭐ 功能请求
description: 描述你想要请求的功能
title: '[Feature] '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        # 请求须知

        在请求功能之前，请仔细[检查](https://github.com/BiliRoamingX/BiliRoamingX/issues?q=label%3Aenhancement)此功能是否已经请求过，避免重复请求。

  - type: textarea
    attributes:
      label: 原因
      description: 遇到了什么问题，为什么想要这个功能
    validations:
      required: true

  - type: textarea
    attributes:
      label: 功能简述
      description: 想要个怎样的功能
    validations:
      required: true

  - type: textarea
    attributes:
      label: 功能逻辑
      description: 如何互交、如何使用等
    validations:
      required: true

  - type: textarea
    attributes:
      label: 实现参考
      description: 该功能可能的实现方式，或者其他已经实现该功能的应用等
    validations:
      required: false
