name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@main
        with:
          pr-title-template: 'build(deps): bump gradle from %sourceVersion% to %targetVersion%'
